baseURL = "https://fourducks.ml/"
languageCode = "en-us"
title = "Varun Malyala"
theme = "archie"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Generalist Developer <br> Product Manager"
#    customcss = ["table.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vmly"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/varunmalyala/"

[[params.social]]
name = "Kaggle"
icon = "link"
url = "https://www.kaggle.com/varunmalyala"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "Resume"
url = "/resume"
weight = 5