baseURL = "https://fourducks.ml/"
languageCode = "en-us"
title = "Varun Malyala"
theme = "hyde"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=5 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Generalist Developer <br> Product Manager"
  # customcss = ["table.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Social Tags



[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/vmly"

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/varunmalyala/"

[[params.social]]
name = "Kaggle"
icon = "link"
url = "https://www.kaggle.com/varunmalyala"

[Menus]
  main = [
      {Name = "All posts", URL = "/posts"},
      {Name = "About", URL = "/about"},
      {Name = "Resume", URL = "https://docs.google.com/document/d/12GwNmNI5WDyB4iR471M18ILKA4KDMhEKDc58x2I6M6g/edit?usp=sharing"},
      {Name = "Github", URL = "https://github.com/vmly/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/varunmalyala/"}
  ]